version: '3.8'
services:
  crm-backend:
    build: ./backend
    container_name: qs-crm-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://quantum_user:Qs2024Secure!@host.docker.internal:5433/quantum_surety
      - RESEND_API_KEY=${RESEND_API_KEY}
      - PORT=4000
    ports:
      - "4001:4000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
  crm-frontend:
    build: ./frontend
    container_name: qs-crm-frontend
    restart: unless-stopped
    ports:
      - "8095:80"
    depends_on:
      - crm-backend
