import express from 'express';
import cors from 'cors';
import { contactsRouter } from './routes/contacts.js';
import { emailRouter } from './routes/email.js';
import { importRouter } from './routes/import.js';
import { campaignsRouter } from './routes/campaigns.js';
import { notariesRouter } from './routes/notaries.js';
import { unsubscribeRouter } from './routes/unsubscribe.js';
import { pipelineRouter } from './routes/pipeline.js';
import { dripRouter } from './routes/drip.js';
import { authRouter } from './routes/auth.js';
import { trackingRouter } from './routes/tracking.js';
import { analyticsRouter } from './routes/analytics.js';
import { notaryCampaignsRouter } from './routes/notary-campaigns.js';

const app = express();
app.use(cors({ origin: '*' }));
app.use(express.json({ limit: '50mb' }));
app.get('/health', (req, res) => res.json({ status: 'ok' }));
app.use('/api/contacts', contactsRouter);
app.use('/api/email', emailRouter);
app.use('/api/import', importRouter);
app.use('/api/campaigns', campaignsRouter);
app.use('/api/notaries', notariesRouter);
app.use('/api/notary-campaigns', notaryCampaignsRouter);
app.use('/api/unsubscribe', unsubscribeRouter);
app.use('/api/pipeline', pipelineRouter);
app.use('/api/drip', dripRouter);
app.use('/api/analytics', analyticsRouter);
app.use('/api/auth', authRouter);
app.use('/api/tracking', trackingRouter);
app.listen(process.env.PORT || 4000, () => console.log('CRM backend running'));
